@startuml Diagram

'Needs the PlantUML extension to be seen

class User
User : int uuid
User : str email
User : int group_id

class Song
Song : str title
Song : str artist
Song : int length
Song : str supervisor
Song : str voice
Song : str guitar
Song : str keys
Song : str drums
Song : str bass
Song : str violin
Song : str cello
Song : str contrabass
Song : str accordion
Song : str flute
Song : str saxophone
Song : str horn
Song : str notes

class SchoolEvent
SchoolEvent : int uuid
SchoolEvent : int group_id
SchoolEvent : int start_time
SchoolEvent : int end_time
SchoolEvent : int duration
SchoolEvent : str subject

@enduml