services:
    artebot:
        build:
        container_name: artedev
        volumes:
            - data_volume:/data
            - db_volume:/database
        env_file: .env
        restart: unless_stopped

volumes:
    data_volume:
    db_volume:
