services:
    app:
        image: gibson-registry.telecomnancy.univ-lorraine.fr/paul.musial/artebot
        container_name: artedev
        volumes:
            - data_volume:/app/data
            - db_volume:/app/database
            - ./token.json:/app/token.json
            - ./credentials.json:/app/credentials.json
        env_file: .env
        restart: unless-stopped

volumes:
    data_volume:
    db_volume:

