services:
    artebot:
        build: .
        container_name: artedev
        volumes:
            - data_volume:/app/data
            - db_volume:/app/database
        env_file: .env
        restart: unless-stopped

volumes:
    data_volume:
    db_volume:

